
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-sa
---
apiVersion: v1
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jupyter-role-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: jupyter-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      serviceAccountName: jupyter-sa
      containers:
      - name: server
        image: jupyter/pyspark-notebook
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "0.5"
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1"
        ports:
        - name: jupyter-port
          containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: jupyter-port
  selector:
    app: jupyter
